<?php

namespace Database\Seeders;

use App\Models\LanguageExecutionProfile;
use Illuminate\Database\Seeder;

class LanguageExecutionProfileSeeder extends Seeder
{
    public function run(): void
    {
        $profiles = [
            [
                'identifier' => 'python',
                'display_name' => 'Python 3.12',
                'file_extension' => '.py',
                'source_filename' => 'main.py',
                'docker_image' => 'python:3.12-alpine',
                'compile_command' => null,
                'run_command' => 'python main.py',
                'execution_mode' => 'interpreted',
                'timeout_seconds' => 10,
                'memory_limit_mb' => 256,
                'cpu_limit' => 1,
                'network_enabled' => false,
                'enabled' => true,
                'environment_variables' => ['PYTHONUNBUFFERED' => '1'],
                'allowed_files' => ['*.py'],
            ],
            [
                'identifier' => 'c',
                'display_name' => 'C (GCC 13)',
                'file_extension' => '.c',
                'source_filename' => 'main.c',
                'docker_image' => 'gcc:13',
                'compile_command' => 'gcc -std=c11 -o main main.c',
                'run_command' => './main',
                'execution_mode' => 'compiled',
                'timeout_seconds' => 15,
                'memory_limit_mb' => 256,
                'cpu_limit' => 1,
                'network_enabled' => false,
                'enabled' => true,
                'environment_variables' => [],
                'allowed_files' => ['*.c', '*.h'],
            ],
            [
                'identifier' => 'cpp',
                'display_name' => 'C++ (GCC 13)',
                'file_extension' => '.cpp',
                'source_filename' => 'main.cpp',
                'docker_image' => 'gcc:13',
                'compile_command' => 'g++ -std=c++17 -o main main.cpp',
                'run_command' => './main',
                'execution_mode' => 'compiled',
                'timeout_seconds' => 15,
                'memory_limit_mb' => 256,
                'cpu_limit' => 1,
                'network_enabled' => false,
                'enabled' => true,
                'environment_variables' => [],
                'allowed_files' => ['*.cpp', '*.hpp', '*.h'],
            ],
            [
                'identifier' => 'java',
                'display_name' => 'Java 21',
                'file_extension' => '.java',
                'source_filename' => 'Main.java',
                'docker_image' => 'eclipse-temurin:21-jdk',
                'compile_command' => 'javac Main.java',
                'run_command' => 'java Main',
                'execution_mode' => 'compiled',
                'timeout_seconds' => 15,
                'memory_limit_mb' => 512,
                'cpu_limit' => 1,
                'network_enabled' => false,
                'enabled' => true,
                'environment_variables' => ['_JAVA_OPTIONS' => '-Xmx256m'],
                'allowed_files' => ['*.java'],
            ],
            [
                'identifier' => 'javascript',
                'display_name' => 'JavaScript (Node.js 20)',
                'file_extension' => '.js',
                'source_filename' => 'main.js',
                'docker_image' => 'node:20-alpine',
                'compile_command' => null,
                'run_command' => 'node main.js',
                'execution_mode' => 'interpreted',
                'timeout_seconds' => 10,
                'memory_limit_mb' => 256,
                'cpu_limit' => 1,
                'network_enabled' => false,
                'enabled' => true,
                'environment_variables' => [],
                'allowed_files' => ['*.js', '*.json'],
            ],
            [
                'identifier' => 'php',
                'display_name' => 'PHP 8.3',
                'file_extension' => '.php',
                'source_filename' => 'main.php',
                'docker_image' => 'php:8.3-cli',
                'compile_command' => null,
                'run_command' => 'php main.php',
                'execution_mode' => 'interpreted',
                'timeout_seconds' => 10,
                'memory_limit_mb' => 256,
                'cpu_limit' => 1,
                'network_enabled' => false,
                'enabled' => true,
                'environment_variables' => [],
                'allowed_files' => ['*.php'],
            ],
            [
                'identifier' => 'go',
                'display_name' => 'Go 1.22',
                'file_extension' => '.go',
                'source_filename' => 'main.go',
                'docker_image' => 'golang:1.22-alpine',
                'compile_command' => 'go build -o main main.go',
                'run_command' => './main',
                'execution_mode' => 'compiled',
                'timeout_seconds' => 15,
                'memory_limit_mb' => 256,
                'cpu_limit' => 1,
                'network_enabled' => false,
                'enabled' => true,
                'environment_variables' => ['CGO_ENABLED' => '0'],
                'allowed_files' => ['*.go'],
            ],
            [
                'identifier' => 'kotlin',
                'display_name' => 'Kotlin 2.0 (JDK 21)',
                'file_extension' => '.kt',
                'source_filename' => 'Main.kt',
                'docker_image' => 'eclipse-temurin:21-jdk',
                'compile_command' => 'kotlinc Main.kt -include-runtime -d main.jar',
                'run_command' => 'java -jar main.jar',
                'execution_mode' => 'compiled',
                'timeout_seconds' => 20,
                'memory_limit_mb' => 512,
                'cpu_limit' => 1,
                'network_enabled' => false,
                'enabled' => true,
                'environment_variables' => ['_JAVA_OPTIONS' => '-Xmx256m'],
                'allowed_files' => ['*.kt'],
            ],
            [
                'identifier' => 'rust',
                'display_name' => 'Rust 1.79',
                'file_extension' => '.rs',
                'source_filename' => 'main.rs',
                'docker_image' => 'rust:1.79-alpine',
                'compile_command' => 'rustc main.rs',
                'run_command' => './main',
                'execution_mode' => 'compiled',
                'timeout_seconds' => 30,
                'memory_limit_mb' => 256,
                'cpu_limit' => 1,
                'network_enabled' => false,
                'enabled' => true,
                'environment_variables' => [],
                'allowed_files' => ['*.rs'],
            ],
        ];

        foreach ($profiles as $profile) {
            LanguageExecutionProfile::updateOrCreate(
                ['identifier' => $profile['identifier']],
                $profile
            );
        }

        $this->command->info('Seeded ' . count($profiles) . ' language execution profiles.');
    }
}